networks:
  cluster:
    name: cluster

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=articles
      - POSTGRES_USER=dcaetano
      - POSTGRES_PASSWORD=secret
    networks:
      - cluster
    ports:
      - 5432:5432
    restart: always
